###############################################################
# Program:
#     Assignment 09, Binary Search Tree
#     Brother Kirby, CS235
# Author:
#     Aiden/Garrett/Ian
# Summary:
#     <put a description here>
# Time:
#     Aiden:   2 hours
#     Garrett: 6 hours
#     Ian:     2 hours
#     Group:   2 hours
# The most difficult part:
#     Aiden: Rotation is a very difficult concept to wrap
#            my head around....
#     Garrett: 
#     Ian: I was having some issues with operator overloading
#          this week and figuring out the nested node. 
###############################################################

##############################################################
# The main rule
##############################################################
a.out: assignment09.o
	g++ -o a.out assignment09.o -g -std=c++11
	tar -cf assignment09.tar *.h *.cpp makefile

##############################################################
# The individual components
#      assignment09.o     : the driver program
##############################################################
assignment09.o: bst.h assignment09.cpp
	g++ -c assignment09.cpp -g -std=c++11


