###############################################################
# Program:
#     Assignment 06, NODE
#     Brother Kirby, CS235
# Author:
#     Garrett Smith & Aiden Reid & Ian Stubbs
# Summary:
#     TO DO
# Coding Time:
#     Pair: 
#     Garrett: 
#     Ian: 
#     Aiden:
#
# The most difficult part:
#     Aiden: 
#     Garrett:
#     Ian: 
###############################################################




##############################################################
# The main rule
##############################################################
a.out: node.h assignment06.o 
	g++ -o a.out assignment06.o  -g -std=c++11
	tar -cf assignment06.tar *.h *.cpp makefile

##############################################################
# The individual components
#      assignment06.o      : the driver program
#      <anything else?>
##############################################################
assignment06.o: node.h assignment06.cpp sortInsertion.h
	g++ -c assignment06.cpp -g -std=c++11
